<?php
// ===========================
// FILE: config.php
// ===========================
// System configuration file
// DO NOT MODIFY - This file is generated by install.php
// Delete this file and run install.php to reconfigure

// These constants will be defined during installation
// If you're seeing errors, run: https://yourdomain.com/install.php

if (!defined('DB_HOST')) {
    die('Configuration Error: Please run install.php to set up the application');
}
?>
