CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) UNIQUE,
 email VARCHAR(100),
 password VARCHAR(255),
 avatar VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE links (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 short_code VARCHAR(10) UNIQUE,
 long_url TEXT,
 views INT DEFAULT 0
);

CREATE TABLE bio_links (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 title VARCHAR(100),
 url VARCHAR(255)
);
